version: '2'
services:
    battleship:
        build: .
        ports:
            - "3000:3000"
        environment:
            - "db=mongodb://battleShip:123@battleship-db:27017/battleShip"
        depends_on:
            - "battleship-db"    
    battleship-db:
        image: aashreys/mongo-auth:latest
        environment:
            - AUTH=yes
            - MONGODB_ADMIN_USER=root
            - MONGODB_ADMIN_PASS=password
            - MONGODB_APPLICATION_DATABASE=battleShip
            - MONGODB_APPLICATION_USER=battleShip
            - MONGODB_APPLICATION_PASS=123
        ports:
             - 27017:27017
